### ISSUE TITLE
Permission system

### ISSUE THREAD

**Issue by ducc** [ducc/dabDiscord#3]
- [x] bit flags
- [x] gateway implementation
- [x] commands
  `perms` show usage/link to wiki
  `perms allow <role> info` allow role to use info commands
  `perms deny <role> manage music` deny role from managing music
  `perms allow everyone play music` allow everyone to play music
  `perms reset` reset perms for server (request confirmation)
  `perms reset <role>` reset role permissions (delete from db)
  play, play music, play_music, PLAY_MUSIC, music play, play songs etc
- [x] permission checks

**Comment by sponges** [comment]
https://github.com/sponges/dabBotDiscord/commit/069c60943a32777d64d182810d514fc33dcce27e

**Comment by sponges** [comment]
Bring back the complex system!

**Comment by ducc** [comment]
Enhancement: permission for each [sub]command
